OpenCyphal-Garage/libcyphal

README.md
Added links to GTest library install guides
=> Adding more install instructions

.travis.yml, CMakeLists.txt, libuavcan/CMakeLists.txt, libuavcan/include/uavcan/build_config.hpp
Opening PR to track discussion; I'll update this with the timing-sensitive tests prior to merge.
=> Adding CONTINUOUS_INTEGRATION_BUILD flag

libuavcan_drivers/posix/include/uavcan_posix/firmware_version_checker.hpp
https://github.com/mavlink/mavlink/pull/414#issuecomment-120088482
The stale comment has led to much misunderstanding .
=> Fixed comment to match

libuavcan_drivers/stm32/driver/include/uavcan_stm32/can.hpp, libuavcan_drivers/stm32/driver/src/uc_stm32_can.cpp
=> Returning meaningful error codes from STM32 CAN driver methods

CMakeLists.txt, libuavcan/CMakeLists.txt, libuavcan/dsdl_compiler/libuavcan_dsdlc
Right now every single incremental PX4 build reruns dsdl_compiler/libuavcan_dsdlc.
=> cmake only run libuavcan_dsdlc if there are changes

libuavcan_drivers/stm32/driver/include/uavcan_stm32/build_config.hpp, libuavcan_drivers/stm32/driver/include/uavcan_stm32/thread.hpp, libuavcan_drivers/stm32/driver/src/internal.hpp, libuavcan_drivers/stm32/driver/src/uc_stm32_can.cpp, libuavcan_drivers/stm32/driver/src/uc_stm32_clock.cpp, libuavcan_drivers/stm32/driver/src/uc_stm32_thread.cpp
added support for FreeRTOS. New macro are added (UAVCAN_SMT32_FREERTOS).
=> support for FreeRTOS

libuavcan_drivers/stm32/driver/include/uavcan_stm32/can.hpp, libuavcan_drivers/stm32/driver/src/uc_stm32_can.cpp
According to https://github.com/UAVCAN/libuavcan/issues/58
=> stm32 driver configuration of filters

libuavcan_drivers/stm32/driver/src/uc_stm32_can.cpp
=> Fixed the CAN acceptance filter initialization in the STM32 driver

libuavcan_drivers/linux/include/uavcan_linux/socketcan.hpp
=> Fixed failing build when socket.h adds flexible arrays to end of structures

libuavcan_drivers/stm32/driver/src/uc_stm32_can.cpp, libuavcan_drivers/stm32/driver/src/uc_stm32_thread.cpp
The changes are fairly minimal.
=> STM32 ChibiOS 18 support

.clang-format
Helps conform to Zubax coding standards https://kb.zubax.com/pages/viewpage.action?pageId=2195699
=> Adding clang-format per #144

.gitmodules, .travis.yml, CMakeLists.txt
Hi Pavel,
This add the FlexCAN driver for uavcan. I have more testing to do but it is communicating. I still have to code the filters.
=> kinetis:UAVCAN driver

libuavcan_drivers/posix/include/uavcan_posix/dynamic_node_id_server/file_storage_backend.hpp
Fixes the issue reported in #74. This was caused by the failure of `mkdir` to create the specified directory because leading directories didn't exist. The patch proposed creates leading directories from top to bottom to ensure the whole tree is setup properly.
=> Fix path creation when parent doesn't exist

Vagrantfile
Forgot to echo the cmake environment variables into the interactive
login profile.
=> Fixing Vagrant environment

.gitignore, .travis.yml, README.md, Vagrantfile, build_steps/configure.sh, build_steps/environment.sh, build_steps/provision.sh, libuavcan/CMakeLists.txt
Not sure if this actually works but the only way to try it out is to merge (because secure keys aren't available to pull-requests)
=> Adding coveralls support

README.md, build_steps/configure.sh
Also eliding references to "realtime" tests. We won't be writing timing
sensitive unit tests again. I'll work on a realtime/on-target testing
strategy that isn't so delicate.
=> REAME fixes per Pavel's feedback.

README.md
Adding documentation for how the top-level folder structure should work
for the bluesky branch. Also adding guidance for target support we plan
on adding to the project as part of the initial release.
=> Documenting top-level folders and targets.

Vagrantfile
Just tried to build a fresh branch and ran into a couple of Vagrant issues. This should fix them.
=> small fixes to Vagrant configuration

README.md
=> fixing typo (nunavut)

.buildkite/pipeline.yml, ci/postbuild-upload-coverage.sh, ci/postbuild-upload-docs.sh
I broke the doc upload step when I got coverage upload working. This should fix it.
=> fixing doc upload

docker/coveralls/info_to_coveralls, docker/coveralls/setup.py
You can ignore this pavel. Just another attempt to get friggen coverage metrics right.
=> Adding coverage fixes to docker

libuavcan_drivers/linux/include/uavcan_linux/socketcan.hpp
See https://github.com/UAVCAN/libuavcan/issues/279
=> increase the number of packets in socketcan driver waiting loopback

.gitmodules, libuavcan/CMakeLists.txt, libuavcan_drivers/stm32/driver/src/internal.hpp
Pr based on request here https://github.com/PX4/libuavcan/pull/3#issuecomment-605483566
=> PX4 legacy-v0 downstream changes

.github/workflows/tests.yml, .gitignore, .vscode/settings.json, CMakeLists.txt, build-tools/bin/verify.py, cmake/CMakeCommon.cmake, cmake/modules/Findcetl.cmake, cmake/modules/Findlibcanard.cmake, cmake/modules/Findlibudpard.cmake, cmake/modules/Findnnvg.cmake, cmake/modules/Findpublic_regulated_data_types.cmake, demonstration/linux/include/posix/libcyphal/transport/can/session/input_session.hpp, demonstration/linux/include/posix/libcyphal/transport/can/session/output_session.hpp, demonstration/linux/include/posix/libcyphal/transport/udp/session/input_session.hpp, demonstration/linux/include/posix/libcyphal/transport/udp/session/output_session.hpp, demonstration/linux/include/posix/libcyphal/wrappers/build_config.hpp, docs/examples/CMakeLists.txt, docs/examples/dsdl/example/foo.1.0.dsdl, docs/examples/example_01_hello_world.cpp
I am so ... sick ... of ... cmake!
=> integrating nunavut

include/libcyphal/common/cavl/cavl.hpp
=> Arduino strings defines an F macro for flash strings.
