OpenCyphal-Garage/libcyphal

- libuavcan/dsdl_compiler/libuavcan_dsdlc
When running from the source directory, libuavcan_dsdlc should
use the version of pyuavcan in the source directory instead of
a globally installed version of pyuavcan.
Fixes UAVCAN/uavcan#18
> Prepend pyuavcan in source directory to sys.path

- libuavcan/include/uavcan/std.hpp
uavcan/libuavcan/src/driver/uc_can.cpp
std.hpp:70:37: error: 'std::size_t' has not been declared  
extern int snprintf(char out, **std::size_t** maxlen, const char
Not sure if this is the "correct" fix, but it works
> Has issue will compiling

- README.md
* Add a link to the discussion group so people know where to ask
questions.  This wasn't immediately apparent to me.
* Debated putting it under documentation, but felt weird.
> README: Add link to discussion group

- libuavcan/include/uavcan/node/abstract_node.hpp
* Compliation will fail on small systems with UAVCAN_TINY defined
with the following error:
abstract_node.hpp:123:33: error: 'IRxFrameListener' has not been declared
* Resolve issue by removing unecessary functions.
* Error is revealed and resolved when building test_stm32f107.
> libuavcan: Disable Frame Listener with UAVCAN_TINY

- libuavcan/include/uavcan/transport/can_acceptance_filter_configurator.hpp
- libuavcan/src/transport/uc_can_acceptance_filter_configurator.cpp
- libuavcan/test/transport/can_acceptance_filter_configurator.cpp
I made enum AnonMassagePresence {WithAnonMsg,NoAnonMsg}; as input argument for configureFilters func for explicity.
Also added another case in unit tests for non-anonymous configuration.
> Acceptance filter update for new transport layer

- libuavcan/include/uavcan/build_config.hpp
- libuavcan/include/uavcan/node/global_data_type_registry.hpp
This allows the global data type registry to be disabled if it's not needed, saving 2–4 KiB depending on compilation settings and the data types used.
> Add UAVCAN_NO_GLOBAL_DATA_TYPE_REGISTRY flag

- libuavcan_drivers/stm32/driver/include/uavcan_stm32/can.hpp
- libuavcan_drivers/stm32/driver/src/uc_stm32_can.cpp
- libuavcan_drivers/stm32/test_stm32f107/src/board/board.cpp
- libuavcan_drivers/stm32/test_stm32f107/src/sys/board.h
I'm using this PR to document the problem.
STM32's bxCAN unit seems to have a hardware bug that causes it to lock `CAN_TX` to low (active) level until it is reset again via RCC. One of the ways to trigger it could be roughly as follows:
1. Reset the controller via RCC.
2. Initialize the controller and put it in silent mode, loopback off.
3. Reset the controller via RCC.
4. Initialize the controller and put it in silent mode, loopback off.
5. Make the controller see a CAN frame on the bus.
Note that some of the steps could be missing, because the bug doesn't appear every time, but roughly every one attempt out of ten.
Legend:
* 1 - CAN diff pair
* 2 - `CAN_TX`
* 3 - `CAN_RX`
It can be seen that the controller leaves `CAN_TX` locked until it is reset two seconds later.
The supposed fix …
> STM32 auto bit rate detection fix

- libuavcan/include/uavcan/protocol/node_info_retriever.hpp
Allows access to node status API (`isNodeKnown`, `getNodeStatus` etc) from `NodeInfoRetriever` instances.
> Changed NodeInfoRetriever to inherit publicly from NodeStatusMonitor 

- .travis.yml
To run a Coverity Scan build, push to the `coverity_scan` branch.
ARM test apps are built automatically as part of the test matrix.
> Travis CI configuration (resolves #64)

- libuavcan/include/uavcan/marshal/bit_stream.hpp
- libuavcan/src/marshal/uc_bit_array_copy.cpp
Compiled with this and `-Os`, vectorcontrol goes from 17008 down to 16676 bytes (332 bytes saved).
> Replace bitarrayCopy with a smaller, from-scratch version (resolves #63)

- libuavcan_drivers/linux/CMakeLists.txt
- libuavcan_drivers/linux/include/uavcan_linux/exception.hpp
- libuavcan_drivers/linux/include/uavcan_linux/socketcan.hpp
Features:
- The driver will throw if it's fed a non-existing or malfunctioning interface during initialization.
- When an interface becomes down/disconnected while the node is running, the driver will silently
exclude it from the IO loop and continue to run on the remaining interfaces.
- When all interfaces become down/disconnected, the driver will throw `AllIfacesDownException` from
`SocketCanDriver::select()`.
I will merge it myself.
> Refactored SocketCAN select() call; fixes #83

- libuavcan/include/uavcan/protocol/dynamic_node_id_server/abstract_server.hpp
- libuavcan/include/uavcan/protocol/dynamic_node_id_server/allocation_request_manager.hpp
- libuavcan/include/uavcan/protocol/dynamic_node_id_server/centralized/server.hpp
- libuavcan/include/uavcan/protocol/dynamic_node_id_server/distributed/server.hpp
- libuavcan_drivers/linux/apps/uavcan_dynamic_node_id_server.cpp
This change adds new API to the dynamic node ID allocation server that allows to guess if dynamic node ID allocation is finished. With this information, APM will be able to reduce the UAVCAN sensor initialization delay to the bare minimum. This PR also brings some minor collateral refactoring (see commit messages).
The changes have been tested on Linux successfully, and the PR is ready for merge.
@hsteinhaus
> Monitoring activity of dynamic node ID allocation servers

- libuavcan_drivers/stm32/driver/src/internal.hpp
@pavel-kirienko 
This is just a second place holder on top of the latest version PX4 is using of libuavcan on their master to build with upstream nuttx
> Do Not merge - This is needed to work with the latest upstream nuttx

- libuavcan_drivers/stm32/driver/src/internal.hpp
- libuavcan_drivers/stm32/driver/src/uc_stm32_can.cpp
#97 
Adds baremetal driver support for STM32F3xx devices whose CAN interrupt names don't have a number. Also adds a link to the STM32 driver documentation next to where `chip.h` is included.
> STM32F303 support for baremetal driver

- libuavcan/include/uavcan/build_config.hpp
With gcc versions superior to 7, the warning -Wexpansion-to-defined is issued. It prevents compilation of PX4.
This PR removes the warning.
> Fix -Wexpansion-to-defined

- libuavcan_drivers/stm32/driver/src/uc_stm32_can.cpp
> Fix redefined IRQ handler in CAN driver for STM32F3 + ChibiOS

- libuavcan/include.mk
- libuavcan/src/marshal/uc_bit_stream.cpp
Build failed with -Wsign-conversion -Werror.  The offending conversion isn't necessary since it's testing equality to positive-one.
The redundant path delimiter is not a bug, more a minor style issue.  Feel free to ignore that commit.
> Minor fixes: unnecessary sign conversion, redundant path delimiter.

- libuavcan/include/uavcan/marshal/array.hpp
Rename variable "ch" to "chr" to avoid shadow variable in ChibiOS. There is a global variable in ChibiOS called "ch" so when a local variable in UAVCAN is called the same name there is a shadowing compile warning. It's never a real conflict but it causes a bunch of compiler warnings. Simply renaming the local variable solves it.
> Rename variable "ch" to "chr" to avoid shadow variable in ChibiOS

- libuavcan/dsdl_compiler/libuavcan_dsdl_compiler/data_type_template.tmpl
- libuavcan/test/dsdl_test/dsdl_uavcan_compilability.cpp
- libuavcan/test/dsdl_test/root_ns_a/UnionTest4.uavcan
Report from Juha Kuikka @kuikka on [Gitter](https://gitter.im/UAVCAN/general) and the [mailing list](https://groups.google.com/d/msgid/uavcan/4df274d9-1822-41e1-bd95-03f1ba30d007%40googlegroups.com?utm_medium=email&utm_source=footer).
> I'm seeing what looks like a bug with unions in messages. This issue is visible when I am trying to communicate between libuavcan and pyuavcan. I have an union with 4 members but the tag comes out to 3 bits by libuavcan due to `typedef ::uavcan::IntegerSpec< ::uavcan::IntegerBitLen< 4 >::Result, ::uavcan::SignednessUnsigned, ::uavcan::CastModeTruncate > TagType;` this is because `IntegerBitLen<4>::Result` evaluates to 3, which makes the tag size. The python side seems to set it to 2 bits because incoming data is off by a bit.
Concerning this:
> The …
> DSDL union tag code generation bug fix

- libuavcan_drivers/stm32/driver/src/uc_stm32_thread.cpp
this prevents us chewing all the cpu when asking for fast spin times
> stm32: allow for less than 1ms wait time on ChibiOS

- .gitignore
- .travis.yml
- CMakeLists.txt
- CMakeLists.txt.in
- libuavcan/CMakeLists.txt
- libuavcan/test/helpers/heap_based_pool_allocator.cpp
Problem:
It's really hard to get Libuavcan tests building on a mac or other platform if googletest isn't installed.
Solution:
add "if linux" guards to problem areas. Also include googletest as recommended in the googletest project's README.
Testing:
Successfully built on OSX sierra using gcc6
> #132 proper googletest dependency and fixes for unittests on OSX

- libuavcan_drivers/stm32/driver/src/internal.hpp
- libuavcan_drivers/stm32/driver/src/uc_stm32_can.cpp
- libuavcan_drivers/stm32/driver/src/uc_stm32_clock.cpp
@pavel-kirienko @dagar - I rebased this on current master and tested on FMUv5. 
@pavel-kirienko unless you see any need to carry support for NuttX < 7.22 this shuuld come into master.
> Support upstream NuttX IRQ API changes

- .gitignore
- .travis.yml
- CMakeLists.txt.in
- README.md
- Vagrantfile
- bootstrap.sh
- libuavcan/include/uavcan/util/templates.hpp
Problem:
There is no automated way to setup a build environment.
Solution:
Use Vagrant to pull an Ubuntu image and install the same
prerequisites used on Travis.
Testing:
Full build on my macintosh.
#141
> Issue #141 Add Vagrantfile to automate dev environment

- .travis.yml
- CMakeLists.txt
- README.md
- libuavcan/CMakeLists.txt
- libuavcan/test/node/test_node.hpp
- libuavcan/test/protocol/data_type_info_provider.cpp
- libuavcan/test/protocol/dynamic_node_id_server/distributed/server.cpp
- libuavcan/test/protocol/dynamic_node_id_server/node_discoverer.cpp
- libuavcan/test/protocol/firmware_update_trigger.cpp
- libuavcan/test/protocol/helpers.hpp
- libuavcan/test/protocol/node_info_retriever.cpp
- libuavcan/test/transport/dispatcher.cpp
- libuavcan/test/transport/transfer_buffer.cpp
- libuavcan/test/util/map.cpp
- libuavcan/test/util/multiset.cpp
Problem:
auto_ptr is deprecated.
Solution:
use unique_ptr which is only available in c++11 and newer.
Also fix how unit tests are run as part of the build to keep them from being
deleted when they fail.
Testing:
Unit tests on linux run.
> Issue #100 remove auto_ptr and c++03 support.

- libuavcan/dsdl_compiler/libuavcan_dsdl_compiler/__init__.py
This adds a check for the `StopIteration` exception to return from the generator.
I'm assuming this has to do with: https://www.python.org/dev/peps/pep-0479/
Fixes #167.
> Fix exception with Python 3.7

- CMakeLists.txt
- CMakeLists.txt.in
- Vagrantfile
- build_steps/provision.sh
- libuavcan/include/uavcan/build_config.hpp
- libuavcan/include/uavcan/uavcan.hpp
- test/native/test_build_config.cpp
Time to have this argument.
Also: decided to continue with #ifdef include guards unless you want to
have the pragma argument too?
Other decisions in here:
- bionic as a reference build environment for CI (because xenial is EOL in two years)
- cmake 3.5.1 because that's the default in bionic and it's not all that new either.
> In which we argue about build flags.

- libuavcan/src/transport/uc_can_acceptance_filter_configurator.cpp
On our platform (GCC 4.9.4 for PowerPC), the following fails to compile in debug mode with the extra error checking turned on because for us std::uint32_t is an unsigned long rather than unsigned int.
<redacted>/libuavcan/libuavcan/src/transport/uc_can_acceptance_filter_configurator.cpp: In member function 'int uavcan::CanAcceptanceFilterConfigurator::applyConfiguration()':
<redacted>/libuavcan/libuavcan/src/transport/uc_can_acceptance_filter_configurator.cpp:142:57: error: format '%u' expects argument of type 'unsigned int', but argument 4 has type 'uavcan::uint32_t {aka long unsigned int}' [-Werror=format=]
multiset_configs_.getByIndex(i)->id);
Instead of using %u, using %PRIu32 from cinttypes allows it to compile.
> use PRIu32 instead of %u to for better wformat compliance

- libuavcan/include/uavcan/marshal/scalar_codec.hpp
We tested libuavcan on an NXP MPC5777m with the big endian assert removed and the endian conversion functionality works correctly.  We'd like to remove the endian assert for big endian machines.
> Removed assert for big endian machines.

- ci/native-clang-build-and-test.sh
- ci/native-gcc-build-and-test.sh
- cmake/compiler_flag_sets/native.cmake
- cmake/compiler_flag_sets/native_common.cmake
- cmake/compiler_flag_sets/native_unittest.cmake
- libuavcan_validation_suite/include/lvs/time.hpp
- test/native/test_util_math.cpp
I won't bother you with this one Pavel. Just trying to get real coverage data. This should do the trick.
> running unittests unoptimized

- libuavcan/include/uavcan/util/avl_tree.hpp
- libuavcan/test/util/avl_tree.cpp
This test reproduced the problem and verified that fixing the typo fixes the problem.
> Issue #254, fixing infinite loop in AVL tree

- libuavcan/dsdl_compiler/libuavcan_dsdl_compiler/__init__.py
After updating `uavcan` python library, libuavcan_dsdlc stopped working with import error: `ImportError: No module named uavcan`.
In this PR I simply renamed `uavcan` lib to `pyuavcan_v0` and updated `pyuavcan` submodule because as I understand previous version had different dsdl path. Now it seems to be ok.
> update pyuavcan lib version and name

- .clang-format
- .gitignore
- libcyphal/include/libcyphal/libcyphal.hpp
- libcyphal/include/libcyphal/transport/transport.hpp
- libcyphal/include/libcyphal/transport/udp/ard.h
- libcyphal/include/libcyphal/transport/udp/session/output.hpp
- libcyphal/include/libcyphal/transport/udp/transport.hpp
This is a follow-up to https://github.com/OpenCyphal-Garage/libcyphal/pull/330#pullrequestreview-1563979276
I removed the top-level anonymous node-ID constant of 0xFFFF because it is not as expressive as an empty `std::optional<NodeID>`.
> Trivial suggestions for the Transport layer redesign PR

- cmake/modules/Findcetl.cmake
- include/libcyphal/transport/can/transport.hpp
- include/libcyphal/transport/defines.hpp
- include/libcyphal/transport/udp/transport.hpp
- include/libcyphal/types.hpp
- test/unittest/transport/can/test_can_transport.cpp
- `cetl::VariableLengthArray` is now in use to store CAN transport media interfaces.
- min MTU from all media is reported by the `ICanTransport::getProtocolParams`.
- added corresponding unit tests (to cover `getProtocolParams`).
Also:
- a bit reworked (simplified) canard memory alloc/free
> Implemented `transport::can::TransportImpl::getProtocolParams`

- README.md
- cmake/modules/Findcetl.cmake
- include/libcyphal/transport/can/delegate.hpp
- include/libcyphal/transport/can/media.hpp
- include/libcyphal/transport/can/msg_rx_session.hpp
- include/libcyphal/transport/can/msg_tx_session.hpp
- include/libcyphal/transport/can/svc_rx_sessions.hpp
- include/libcyphal/transport/can/svc_tx_sessions.hpp
- include/libcyphal/transport/can/transport.hpp
- include/libcyphal/transport/contiguous_payload.hpp
- include/libcyphal/transport/msg_sessions.hpp
- include/libcyphal/transport/scattered_buffer.hpp
- include/libcyphal/transport/svc_sessions.hpp
- include/libcyphal/transport/transport.hpp
- include/libcyphal/transport/udp/transport.hpp
- include/libcyphal/types.hpp
- test/unittest/test_utilities.hpp
- test/unittest/transport/can/test_can_delegate.cpp
- test/unittest/transport/can/test_can_msg_rx_session.cpp
- test/unittest/transport/can/test_can_msg_tx_session.cpp
- test/unittest/transport/can/test_can_svc_rx_sessions.cpp
- test/unittest/transport/can/test_can_svc_tx_sessions.cpp
- test/unittest/transport/can/test_can_transport.cpp
- test/unittest/transport/test_scattered_buffer.cpp
No `CETL_NODISCARD` for the most of public api (issue #350), but private (aka `detail`) stuff stays under strict `[[nodiscard]]` policy for all non-`void` returning functions.
Also:
- Less `NOSONAR`-s by switching some internal `void*`-s → `cetl::byte*`-s.
- Eliminated `IMultiplexer` at CAN - no use of it; but will be at UDP.
- More docs for public api.
- Fixed Build Status and Sonar Cloud badges at `README.md`.
> No CETL_NODISCARD for most of the public api

- include/libcyphal/presentation/common_helpers.hpp
- test/unittest/presentation/test_client.cpp
- test/unittest/presentation/test_server.cpp
- test/unittest/presentation/test_subscriber.cpp
This case (namely with zero-length payload) was discovered during my work with the demo app, where I deliberately use special (O1Heap-based) PMR allocator for ALL dynamic allocations.
It turns out that such allocator has special/corner case when payload is empty (which is a totally valid case, f.e. for an RPC service request). So, investigation of this problem also brought attention to quite useful optimization we can have during deserialization.
> Apply small payload deserialize optimization

- docs/examples/2_application/example_2_application_0_node_hb_getinfo_udp.cpp
- docs/examples/platform/storage.hpp
- include/libcyphal/application/registry/registry_impl.hpp
- include/libcyphal/platform/storage.hpp
- test/unittest/application/registry/registry_gtest_helpers.hpp
- test/unittest/application/registry/test_registry.cpp
- test/unittest/platform/storage_key_value_mock.hpp
- Defined abstract key-value storage interface; plus its mock under unit tests.
- Added `load` & `save` methods for persisting registry in a storage; its unit test coverage (100%).
- Extended example_2_app_0 with registry persisting.
> Defined `platform::storage::IKeyValue` interface

- cmake/modules/Findlibcanard.cmake
- docs/examples/platform/linux/can/can_media.hpp
- docs/examples/platform/linux/can/socketcan.c
- include/libcyphal/transport/can/can_transport_impl.hpp
- include/libcyphal/transport/can/delegate.hpp
- include/libcyphal/transport/can/media.hpp
- include/libcyphal/transport/lizard_helpers.hpp
- include/libcyphal/transport/media_payload.hpp
- include/libcyphal/transport/udp/udp_transport_impl.hpp
- test/unittest/sonar.cpp
- test/unittest/transport/can/media_mock.hpp
- test/unittest/transport/can/test_can_msg_tx_session.cpp
- test/unittest/transport/can/test_can_svc_tx_sessions.cpp
- test/unittest/transport/can/test_can_transport.cpp
- test/unittest/transport/test_media_payload.cpp
- Introduced `libcyphal::transport::MediaPayload` - in use to pass payload data between the transport layer and its media.
- Use lates latest Canard v4 api
> Single copy TX pipeline

- include/libcyphal/transport/can/can_transport_impl.hpp
- include/libcyphal/transport/can/delegate.hpp
- include/libcyphal/transport/can/msg_rx_session.hpp
- include/libcyphal/transport/can/msg_tx_session.hpp
- include/libcyphal/transport/can/rx_session_tree_node.hpp
- include/libcyphal/transport/can/svc_rx_sessions.hpp
- include/libcyphal/transport/can/svc_tx_sessions.hpp
- include/libcyphal/transport/session.hpp
- include/libcyphal/transport/session_tree.hpp
- include/libcyphal/transport/svc_rx_session_base.hpp
- include/libcyphal/transport/udp/delegate.hpp
- include/libcyphal/transport/udp/msg_rx_session.hpp
- include/libcyphal/transport/udp/msg_tx_session.hpp
- include/libcyphal/transport/udp/rx_session_tree_node.hpp
- include/libcyphal/transport/udp/session_tree.hpp
- include/libcyphal/transport/udp/svc_rx_sessions.hpp
- include/libcyphal/transport/udp/svc_tx_sessions.hpp
- include/libcyphal/transport/udp/udp_transport_impl.hpp
- include/libcyphal/types.hpp
- test/unittest/transport/can/test_can_delegate.cpp
- test/unittest/transport/can/test_can_svc_rx_sessions.cpp
- test/unittest/transport/can/test_can_transport.cpp
- test/unittest/transport/test_session_tree.cpp
- test/unittest/transport/udp/test_session_tree.cpp
- test/unittest/transport/udp/test_udp_delegate.cpp
- test/unittest/transport/udp/test_udp_svc_rx_sessions.cpp
- test/unittest/transport/udp/test_udp_transport.cpp
1. Response Rx Session now doesn't own lizard's rpc port subscription - instead now session references the shared subscription (with reference counting).
2. Transport delegates now manage subscriptions.
3. CAN Response Rx Sessions now stored in cavl tree (for UDP it was already like this) - matching now by both port and node ids (previously it was by the port only).
4. CAN filters now also are made by the delegate (b/c it knows about subscriptions (see bullet # 2).
5. Extended unit tests to cover multiple response Rx sessions (both CAN and UDP). Also covered unsolicited responses.
Github's Hide whitespaces is recommended.
> Fix for issue #412 Only one single RPC client is possible per port

- include/libcyphal/transport/can/can_transport_impl.hpp
- include/libcyphal/transport/udp/udp_transport_impl.hpp
- test/unittest/transport/can/test_can_transport.cpp
- test/unittest/transport/udp/test_udp_transport.cpp
Fix for issue #438:
- Fixed callback lifetime bug in CAN transport; added unit test to specifically verify TX media callback lifetime.
- Although there is no such issue at UDP transport, still added similar test for udp as well.
> Fixed CAN transport media TX callback lifetime.

- include/libcyphal/config.hpp
- include/libcyphal/transport/can/can_transport_impl.hpp
- include/libcyphal/transport/udp/msg_tx_session.hpp
- include/libcyphal/transport/udp/svc_tx_sessions.hpp
- include/libcyphal/transport/udp/udp_transport_impl.hpp
- include/libcyphal/types.hpp
- test/unittest/custom_libcyphal_config.hpp
- test/unittest/transport/can/test_can_transport_custom_config_millisecs.cpp
- test/unittest/transport/udp/test_udp_transport_custom_config_millisecs.cpp
- `libcyphal::MonotonicClock` type definition is moved under `libcyphal::Config` - now it's possible to customize libcyphal `TimePoint` & `Duration` types.
- Fixed several missing `std::chrono::duration_cast<Duration>` when converting from lizard µsec to libcyphal time.
- Added two new unit tests to ensure that both CAN and UDP transports could be compiled with custom milliseconds-based clock. Without the above `duration_cast` fixes these unit tests are not-compilable.
> Fixes for issues 431 & 399
